export const PLACE_ORDER_RESQUEST="PLACE_ORDER_RESQUEST"
export const PLACE_ORDER_SUCCESS="PLACE_ORDER_SUCCESS"
export const PLACE_ORDER_FAIL="PLACE_ORDER_FAIL"

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST"
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS"
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL"

export const PAYPAL_KEY = 'PAYPAL_KEY'
export const ORDER_PAY_RESET = "ORDER_PAY_RESET"