export const USER_LOGIN_REQUEST="USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS="USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL="USER_LOGIN_FAIL"
export const USER_LOGOUT="USER_LOGOUT"


export const NEW_USER_REGISTER_REQUEST="NEW_USER_REGISTER_REQUEST"
export const NEW_USER_REGISTER_SUCCESS="NEW_USER_REGISTER_SUCCESS"
export const NEW_USER_REGISTER_FAIL="NEW_USER_REGISTER_FAIL"


export const USER_PROFILE_REQUEST="USER_PROFILE_REQUEST"
export const USER_PROFILE_SUCCESS="USER_PROFILE_SUCCESS"
export const USER_PROFILE_REMOVE="USER_PROFILE_REMOVE"
export const USER_PROFILE_FAIL="USER_PROFILE_FAIL"